apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  labels:
    app: echo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: echoheaders-x